vim.opt.number = true -- line numbers
vim.opt.cursorline = true -- highlight the current line
vim.opt.clipboard = "unnamed" -- use system clipboard
vim.opt.list = true -- show whitespace characters
vim.opt.foldmethod ="indent" -- fold based on indentation
vim.opt.foldlevelstart = 99 -- start with all folds open
vim.opt.ignorecase = true -- case-insensitive searching
vim.opt.smartcase = true -- case-sensitive search if uppercase letter typed
vim.opt.scrolloff = 8  -- keep 8 lines visible when scrolling
