" -----------------------------------
" Neema Yousefi's vimrc
" -----------------------------------

set nocompatible
syntax enable
filetype indent on

" ----------Plugins----------

call plug#begin('~/.vim/plugged')

Plug '/opt/homebrew/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-vinegar'
Plug 'christoomey/vim-tmux-navigator'
Plug 'sjl/gundo.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'dense-analysis/ale'
Plug 'sheerun/vim-polyglot'
Plug 'ludovicchabant/vim-gutentags'
Plug 'vim-airline/vim-airline'

call plug#end()

" gutentags using rg to ignore certain files specified in .gitignore
let g:gutentags_file_list_command = 'rg --files'

let g:gundo_close_on_revert = 1
let g:gundo_preview_height = 25
let g:gundo_prefer_python3 = 1

let g:ale_disable_lsp = 1


" ---------UI----------
highlight clear SignColumn
highlight clear ALEErrorSign
highlight clear ALEWarningSign
let g:ale_set_highlights = 0
let g:ale_sign_error = '❌'
let g:ale_sign_warning = '⚠️'

let g:ale_sign_column_always = 1

let g:airline_powerline_fonts = 1
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#tabline#enabled=1

" ----------Keybinds----------
nnoremap U :GundoToggle<CR>
nnoremap <Space> za
nnoremap <F8> :ALEFix<CR>

" ALE goto warinings/errors
nnoremap [g :ALEPreviousWrap<CR>
nnoremap ]g :ALENextWrap<CR>

" makes j and k not skip over wrapped lines
noremap j gj
noremap k gk
noremap gj j
noremap gk k

nnoremap <C-p> :Files<CR>
nnoremap <Leader>t :Tags<CR>
nnoremap <Leader>h :History<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <leader>n :set relativenumber!<CR>
nnoremap <leader>l :set list!<CR>
nnoremap <leader><CR> :nohlsearch<CR>

" refresh vimrc
nnoremap <leader><F5> :source ~/.dotfiles/vimrc<CR>

" Basic Settings
set number
set showcmd
set ruler
set cursorline
set lazyredraw
set wildmenu
set laststatus=2
set nomodeline
set clipboard=unnamed
set backspace=indent,eol,start
set cmdheight=2
set list

" folding
set foldmethod=indent
set foldlevelstart=99

" search
set incsearch
set hlsearch
set ignorecase
set smartcase


" ----------Spacing Functions----------
" spaces over tabs
function! Spaces(tabWidth)
	let &tabstop=a:tabWidth
	let &shiftwidth=a:tabWidth
	let &softtabstop=a:tabWidth
	set expandtab
endfunction

" tabs over spaces
function! Tabs(tabWidth)
	let &tabstop=a:tabWidth
	let &shiftwidth=a:tabWidth
	let &softtabstop=a:tabWidth
	set noexpandtab
endfunction

call Tabs(4)
